AllCops:
  Exclude:
    - 'Gemfile'

  DisplayStyleGuide: true

  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*'
